name: Package application

on:
  push:
    branches:
      - 'dhananjay-build-test'

jobs:
  build-and-package:
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        os:
          # - macos-latest
          - windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: goSprinto/stethoscope-app
          ref: 'dhananjay-build-test'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ${{ runner.home }}/.cache/electron
            ${{ runner.home }}/.cache/electron-builder
          key: ${{ matrix.os }}-dependencies-${{ hashFiles('**/yarn.lock') }}

      - name: Build and Package
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            docker run --rm \
              -e ELECTRON_CACHE="${{ runner.home }}/.cache/electron" \
              -e ELECTRON_BUILDER_CACHE="${{ runner.home }}/.cache/electron-builder" \
              -v ${{ github.workspace }}:/project \
              -v ${{ runner.home }}/.cache/electron:/root/.cache/electron \
              -v ${{ runner.home }}/.cache/electron-builder:/root/.cache/electron-builder \
              electronuserland/builder:18-wine \
              /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn build"
          else
            yarn build:windows
          fi
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Dist
          path: dist
  
      - name: Cleanup old cache
        if: runner.os == 'ubuntu-latest'
        run: rm -rf ${{ runner.home }}/.cache/electron-builder/wine
