name: Package application

on:
  push:
    branches:
      - 'dhananjay-build-test'

jobs:
  sign-windows-executable:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: goSprinto/stethoscope-app
          ref: 'dhananjay-build-test'

      # Compile a simple "Hello World" program and create the example.exe file
      - name: Compile Hello World program
        run: |
            Add-Content -Path example.txt -Value "Hello, world!"
            Rename-Item -Path example.txt -NewName example.exe
          
      # Start PowerShell as Administrator
      # - name: Start PowerShell as Administrator
      #   run: Start-Process powershell -Verb runAs

      # Import Windows certificate
      # - name: Import Windows certificate
      #   env:
      #     WINDOWS_CERTIFICATE: ${{ secrets.P12FILE }}
      #     WINDOWS_CERTIFICATE_PASSWORD: ${{ secrets.PASSWORD }}
      #   run: |
      #     Start-Process powershell -Verb runAs
      #     New-Item -ItemType directory -Path certificate
      #     Set-Content -Path certificate/tempCert.txt -Value $env:WINDOWS_CERTIFICATE
      #     certutil -decode certificate/tempCert.txt certificate/certificate.pfx
      #     Remove-Item -Path certificate -Include tempCert.txt
      #     Import-PfxCertificate -FilePath certificate/certificate.pfx -CertStoreLocation Cert:\CurrentUser\My -Password (ConvertTo-SecureString -String $env:WINDOWS_CERTIFICATE_PASSWORD -Force -AsPlainText)
      
      # # Sign example.exe with signtool
      # - name: Sign example.exe with signtool
      #   run: |
      #     "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe" sign /f "certificate/certificate.pfx" /p ${{ secrets.P12_PASSWORD }} /tr http://timestamp.sectigo.com /td sha256 /fd sha256 /sha1 ${{ secrets.SHA1KEY }} "example.exe"
      
      # Save artifacts
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Dist-windows
          path: dist
          
      - name: Sign binary
        uses: lando/code-sign-action@v2
        with:
          file: dist
          certificate-data: ${{ secrets.P12FILE }}
          certificate-password: ${{ secrets.PASSWORD }}
